eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${discovery.url}

spring:
  cloud:
    gateway:
      routes:
        - id: user-service-login
          uri: 'lb://USER-SERVICE'
          filters:
            - UserRole=
          predicates:
            - Path=/users/login
        - id: user-service-info
          uri: 'lb://USER-SERVICE'
          filters:
            - UserRole=ROLE_ADMIN
          predicates:
            - Path=/users/**
        - id: instrument-service
          uri: 'lb://INSTRUMENT-SERVICE'
          filters:
            - UserRole=ROLE_ADMIN, ROLE_MAINTAINER, ROLE_TRADER
          predicates:
            - Path=/instrument/**
        - id: market-service-docs
          uri: 'lb://MARKET-SERVICE'
          predicates:
            - Path=/market/v3/api-docs
          filters:
            - RewritePath=/market/v3/api-docs, /v3/api-docs
        - id: market-service-create
          uri: 'lb://MARKET-SERVICE'
          filters:
            - UserRole=ROLE_ADMIN, ROLE_MAINTAINER
          predicates:
            - Path=/market
            - Method=POST
        - id: market-service-info
          uri: 'lb://MARKET-SERVICE'
          filters:
            - UserRole=ROLE_ADMIN, ROLE_MAINTAINER, ROLE_TRADER
          predicates:
            - Path=/market/**
        - id: market-instrument-id-service
          uri: 'lb://MARKET-INSTRUMENT-ID-SERVICE'
          filters:
            - UserRole=ROLE_ADMIN, ROLE_MAINTAINER, ROLE_TRADER
          predicates:
            - Path=/marketInstrumentId/**
        - id: market-service-docs
          uri: 'lb://TRADE-SERVICE'
          predicates:
            - Path=/trade/v3/api-docs
          filters:
            - RewritePath=/trade/v3/api-docs, /v3/api-docs
        - id: trade-service
          uri: 'lb://TRADE-SERVICE'
          filters:
            - UserRole=ROLE_ADMIN, ROLE_MAINTAINER, ROLE_TRADER
          predicates:
            - Path=/trade/**
        - id: portfolio-service
          uri: 'lb://TRADE-SERVICE'
          filters:
            - UserRole=ROLE_ADMIN, ROLE_MAINTAINER, ROLE_TRADER
          predicates:
            - Path=/portfolio/**
        - id: order-service
          uri: 'lb://ORDER-SERVICE'
          filters:
            - UserRole=ROLE_ADMIN, ROLE_MAINTAINER, ROLE_TRADER
          predicates:
            - Path=/order/**
jwt:
  secret: "SS1GVUNLSU5HLUxPVkUtU1BSSU5HLUFORC1IT1ctSVQtSVMtTElURVJBTExZLU1BR0lDQUxMWS1XT1JLUy1BTkQtRkFJTFMtV0lUSC1DUllQVElELUVYQ0VQVElPTlM="
